### ISSUE TITLE
屏幕键盘工具栏无法使用

### ISSUE THREAD

**Issue by Yue1u** [hugeBlack/OpenParsec#10]
https://github.com/user-attachments/assets/a3249f31-de54-4069-928e-365378945c45

**Comment by hugeBlack** [comment]
设备型号和系统版本是什么？

**Comment by Yue1u** [comment]
iPhone 8 Plus IOS 16.5.1（c）
iPhone SE IOS 16.6.1

**Comment by hugeBlack** [comment]
鉴定为老系统的特有bug，新版本我在iOS15.8.3测试没问题了，你再下载试试？
