### ISSUE TITLE
OpenParsec中的鼠标不跟随Host上的鼠标移动

### ISSUE THREAD

**Issue by ElectricDogCN** [hugeBlack/OpenParsec#12]
12.9寸 iPad Pro 第1代 (2015)
iPadOS 16.7.10 (20H350)
OpenParsec Release @ 20241025
Parsec Release @ Build 150-95e

在OpenParsec中可以控制Host上的鼠标正常移动，OpenParsec上鼠标显示也正常，但是如果直接控制Host上的鼠标OpenParsec里的鼠标图标不会跟随移动.

**Comment by hugeBlack** [comment]
原版的Parsec中鼠标也不跟随Host上的鼠标移动吧？
