### ISSUE TITLE
播放卡顿

### ISSUE THREAD

**Issue by augurz** [hugeBlack/OpenParsec#13]
相同网络下mini5播放会一卡一卡的，画面也不清晰很多压缩块，天玑800的手机就很流畅。另外openparsec链接建立之后，串流从4:2:0fullrange回落到非全范围，是老客户端不兼容新特性吗，需要怎么调整？

**Comment by hugeBlack** [comment]
关掉附近的所有mac，然后重启你的设备，再试试，这是苹果的awdl的问题，无法解决。串流应该就是用的4:2:0，还是说你用了4:4:4？

**Comment by augurz** [comment]
不，是安卓端overlay会显示fullrange openparsec连上以后fullrange会消失

**Comment by augurz** [comment]
关了蓝牙，卡顿好了，学到新知识了，感谢
