### ISSUE TITLE
Couple Feature Requests

### ISSUE THREAD

**Issue by iamse7en** [hugeBlack/OpenParsec#5]
Thank you for your work on this, this works great! I have a few requests, not sure how easy or hard they would be to add.

1) Every time I connect to my Windows PC, it requests 1080p and changes my Windows system resolution. I have to manually change to the resolution back to my preferred 2160p. This does not happen when I connect to my Mac. I wonder if it's because I have a virtual screen on my Mac, but not my PC. Instead my Windows PC uses an HDMI headless dongle. It does not do this on the official macOS Parsec app. Maybe I need to install [VDD](https://github.com/itsmikethetech/Virtual-Display-Driver) on my Windows machine to solve this problem. 

2) I use several RDP/VNC apps Jump Desktop or Screens 5 on iOS, as well as Moonlight. All of these apps allow you to change the gesture mode from Touch (where you cannot move the mouse with your finger, but you just tap on the screen where you want to -  this is how OpenParsec is currently configured) to Trackpad, where you drag your finger across the screen to move the mouse, then single finger tap for left click or double finger tap for right click, or 2 finger scroll for mouse scroll. When you only have your finger, touch mode is severely limited. For example, look at this screenshot. Due to the iOS bar at the bottom, I cannot tap anywhere on my taskbar or on the search bar. It really needs to have trackpad mode.

![image](https://github.com/user-attachments/assets/f7452cb0-31ae-4335-9073-c7262d28271e)

3) Support for game controllers/gamepads? Parsec is great for gaming, would love to have this feature added.

Thanks again! This version of OpenParsec already far ahead of where the @AngelDTF (now deleted) repo was. Great work!

**Comment by hugeBlack** [comment]
Thank for your feedback! 
1. You can now set default resolution in settings, as well as set bitrate and resolution during streaming. 
2. Touchpad mode is supported now.
3. Game controllers are already supported. Just connect your controller, press any trigger button during streaming and parsec will detect it.
Please download the latest build and have a try. Let me know if you still have any suggestion!

**Comment by iamse7en** [comment]
Thank you, this is great, thank you! I just tested it. One issue is with Touchpad mode (other VNC apps call it Trackpad mode, since it behaves like a trackpad on a laptop). It does now work to drag my finger to move the cursor. However, as soon as you lift your finger and touch the screen again, it moves the cursor to exactly where you touched. This makes it a mixture of Touch mode and Trackpad mode, which is confusing. The mouse should still stay where it already is, and it only moves as you drag your finger and not re-locate to the place where you touch.

**Comment by hugeBlack** [comment]
Can't reproduce. Mouse cursor never moved to where I touched in touchpad mode in my test. Did you enabled touchpad mode in settings? If so, please send a video that shows both your finger and screen so I can diagnose what's wrong.

**Comment by iamse7en** [comment]
Thank you. Where can I enable touchpad mode? In iPhone client settings or Computer host settings? I don't see it in either.

**Comment by hugeBlack** [comment]
![IMG_3062](https://github.com/user-attachments/assets/ef72dbf8-f871-45ce-87db-cc55dbbc79ba)
It's here in the client settings if you are using the latest release.

**Comment by iamse7en** [comment]
Oh thanks! I was using Build #10 I think... I'll install #11
