### ISSUE TITLE
Feature Request: Virtual Keyboard and Setting Video Resolution

### ISSUE THREAD

**Issue by EnderRobber101** [hugeBlack/OpenParsec#8]
would it be possible to add an option to choose a resolution when limited in bandwith. It defaults to 4k on my phone. Also a virtual keyboard support would be greatly appreciated as i need to carry a separate keyboard. Thanks! This is an amazing project!

**Comment by hugeBlack** [comment]
Done in latest build. You can download and have a try.

**Comment by d5aqoep** [comment]
@hugeBlack 
I am unable to use built in iOS keyboard in the latest version on both iOS and iPad OS. How can I bring up the keyboard to enter password?
