### ISSUE TITLE
连接成功但黑屏

### ISSUE THREAD

**Issue by jiege6-66** [hugeBlack/OpenParsec#9]
ipad pro 12.9 2021 ios18 
链接成功，能在电脑端看到接入设备，pad屏幕是黑的

**Comment by hugeBlack** [comment]
你用其他设备连接能否连上？

**Comment by jiege6-66** [comment]
我目前设备基本都是ios，windwos是arm的，之前测试可以连接，还有个Y700平板之前也是可以正常连接的（显示没问题）

**Comment by hugeBlack** [comment]
感觉是host端的parsec没有开始编码，你把host端的parsec重启一下再试试，然后再试试其他设备能否连接。我手里没有woa的设备没法测，不过我的两个pad和手机连接windows和mac都没遇到问题

**Comment by jiege6-66** [comment]
ok，也有可能，我再去看下host

**Comment by jiege6-66** [comment]
确实，简单问题没发现，多谢
